name: 🐞 Bug report
description: File a bug report
title: "[Bug] - "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug clearly
      required: true
