name: 🐞 Bug report
description: Report a bug
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
      required: true
